### ISSUE TITLE
save multi value / array

### ISSUE THREAD

**Issue by Q8hma** [talut/rn-secure-storage#17]
Hello
does this plugin support save array or multi value ?
and does any way to get all values or get multi values on one time ?

thanks

**Comment by talut** [comment]
Hi, you can save the objects with **JSON. stringify()**  Then you can get values as object with **JSON.parse()**

**Comment by Q8hma** [comment]
no bro im asking about if its ok to save
1- key (username) ,, value (q8hma)
2- key (pass) .. value (123456789)
like this ...
RNSecureStorage.set("username", "q8hma").then((res) => {console.log(res);}, (err) => {console.log(err);});
RNSecureStorage.set("pass", "123456789").then((res) => {console.log(res);}, (err) => {console.log(err);});
or i need to make it array/obj then save it ?

thnx

**Comment by talut** [comment]
@Q8hma  It's all up to you. You can store pass and username one by one or you can store this values as object.

**Comment by Q8hma** [comment]
nice thnx bro
