### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by Q8hma** [talut/rn-secure-storage#18]
Hello
i tried to save and get them but nothings

my code is 
`
import {ReactNative } from 'react-native';
import RNSecureStorage, { ACCESSIBLE } from 'rn-secure-storage'

export function save_user_info(info) {
      RNSecureStorage.set("info", JSON.stringify(info), {accessible: ACCESSIBLE.ALWAYS})
          .then((res) => {
return true;
          }, (err) => {
				console.log(err);
return err;
				});
};

export function get_user_info() {
  RNSecureStorage.get("info").then((val) => {
	 if(val){
return JSON.parse(val);
}else{
return {"userid": 1,"full_name": "Demo Demo","email":"demo@demo.com","token":"81e4247f6c5823ada231cbbbd387a380433ed1a8","actived":true,"phone":"99999999"};
}
          }, (err) => {
				console.log(err);
return {"userid": 1,"full_name": "Demo Demo","email":"demo@demo.com","token":"81e4247f6c5823ada231cbbbd387a380433ed1a8","actived":true,"phone":"99999999"};
				});
};

export default RNSecureStorage;
`

this how i used it
`
import {save_user_info,get_user_info} from '../ultils/user_info.js';
`
`   <Text>{JSON.stringify(save_user_info({
	            'userid': '1',
	            'full_name': 'Demo Demo',
	            'email':'demo@demo.com',
	            'token':'81e4247f6c5823ada231cbbbd387a380433ed1a8',
	            'actived':'1',
	            'phone':'99999999'
	            }))}</Text>
	            <Text>{JSON.stringify(get_user_info())}</Text>`

thnx

**Comment by Q8hma** [comment]
and when i go to console nothing found

**Comment by Q8hma** [comment]
i tried it without function and it work fine
sorry to make the issue
please close it

**Comment by talut** [comment]
@Q8hma This is a async func. You can't return value directly. It will return promise response. Maybe you can set as state the returning value  in here `RNSecureStorage.get("info").then((val) => {` 

```
 RNSecureStorage.get("name").then((value) => {
         this.setState({
name: value
})
        }).catch((err) => {
          console.log(err)
        })

```
