### ISSUE TITLE
RNSecureStorage is undefined

### ISSUE THREAD

**Issue by Asc2011** [talut/rn-secure-storage#20]
Hello, I tried as suggested

`import RNSecureStorage, { ACCESSIBLE } from 'rn-secure-storage'`

somehow the import of the ACCESSIBLE-object arrives, but `RNSecureStorage` is `undefined` ?

What can I do here ? I made sure that evrth. is linked
`react-native link rn-secure-storage`

> rnpm-install info Platform 'ios' module rn-secure-storage is already linked
> rnpm-install info Platform 'android' module rn-secure-storage is already linked

thx and greets, Andreas

**Comment by talut** [comment]
Hi, sorry for late answer. I check the package but can't find any issue. Right now I'm using this package at my own 3 project like mentioned at README.MD

Would please control docs/example usage agai. If its still not work open this issue again.

**Comment by pt7892** [comment]
Getting the same issue with 1.0.9 

`TypeError: Cannot read property 'get' of undefined`
<img width="372" alt="Screen Shot 2019-03-18 at 20 35 38" src="https://user-images.githubusercontent.com/20343932/54558244-8aedd600-49bd-11e9-8985-4408a3bb5906.png">

**Comment by talut** [comment]
@pt7892 Hi, I'm using this package at my own projects. And works fine. I updated 1.0.9 today and updated all my projects. They're working well too.

Did you test the sample application?  Also can you check native project at Xcode or Android Studio to see is linked well? If react-native link not worked you can use manual linking.

Also is your project started from react-native-cli or its an Expo project?

```
import RNSecureStorage, { ACCESSIBLE } from 'rn-secure-storage'       
RNSecureStorage.get("token").then((value) => {
         console.log(value)
        }).catch((err) => {
          console.log(err)
        })
```

**Comment by Asc2011** [comment]
@talut hi again, i had a second dependency in my project. So my bad - after i removed the offending dependency, all went fine. 
thx and greets,
