### ISSUE TITLE
"Failed to obtain information about private key" on Android

### ISSUE THREAD

**Issue by AdamGold** [talut/rn-secure-storage#21]
When trying to save a private key in Android, I keep getting "Failed to obtain information about private key".

According to:
https://stackoverflow.com/questions/36652675/java-security-unrecoverablekeyexception-failed-to-obtain-information-about-priv

It means that the keystore is probably not unlocked.

Any known way to fix this?

**Comment by talut** [comment]
@AdamGold Hi, in what devices/Android version you getting this error? I'm using this package at my own projects (IOS/Android) I didn't not encounter with this error. If I can reproduce the issue I can solve this issue.

**Comment by AdamGold** [comment]
I am using it on an emulator:
``Pixel XL API 27 | 27 | Android 8.1 (Google APIs) | x86 | 4.3 GB``

**Comment by talut** [comment]
@AdamGold I started same emulator with same version but I can't reproduce this issue. Can you please clone & try example app in repo? BTW, I updated example app package version to 1.0.82.

**Comment by AdamGold** [comment]
Found out that changing the key name from Store@key to ``Store_key`` worked. I am now confused whether it was the changing of the ``@`` or it was caused by something else - Maybe Android couldn't override the existing value in Store@key?

**Comment by AdamGold** [comment]
Will do, and I will update if this error happens again - with steps to reproduce. Thank you!

**Comment by talut** [comment]
@AdamGold Thanks actually I should update README for this kinda problems. So thanks for this issue 😄
