### ISSUE TITLE
SetState not working ?

### ISSUE THREAD

**Issue by singhsurma** [talut/rn-secure-storage#22]
Hi ! could  you please explain how we can use this !

I have tried using in my class: 

```
class Authorize {
//results are coming from fetch promise...
   RNSecureStorage.set("UserSessionName", results.session_name, {accessible: ACCESSIBLE.WHEN_UNLOCKED})
                .then((res) => {
                    console.log(res);
                }, (err) => {
                    console.log(err);
                });
}
```

it works in above case but when I use setStat in same function in above class it gives below error: 

> YellowBox.js:67 Possible Unhandled Promise Rejection (id: 0):
> TypeError: _this.setState is not a function
> TypeError: _this.setState is not a function

I tried alternative to setState, when we get values: 

```
componentDidMount(){


        RNSecureStorage.get("UserSessionToken").then((value) => {
            this.setState({
                userToken: value
            })
            console.log(this.state.userToken) // in this it gives value
        }).catch((err) => {
            alert(err)
        })

        console.log(this.state.userToken) // but this outside does not give values, it shows same as set in constructor 

        //Authorize.GetUserRole(this.state.userToken)
         
    }
```

But this also does not works. It give value to console within  RNSecureStorage.get but when called outside it gives no value ie: undefined. 

Please suggest !

**Comment by talut** [comment]
Hi @singhsurma please check example. [https://github.com/talut/rn-secure-storage/blob/893e97563ee51d86e92de2d98af941cfc662dca2/example/App.js#L38](rn-secure-storage/example/App.js)

**Comment by singhsurma** [comment]
Thanks I have gone thorugh already but there was some other reason in my case !! I am new to React and going thorugh other documentation helped me. Now I changed my way to  fetch etc it get solved.
