### ISSUE TITLE
No definitive way to determine if a value exists

### ISSUE THREAD

**Issue by kirin-p** [talut/rn-secure-storage#26]
Hey!

rn-secure-storage offers a great way to save and access data securely within a device. Unfortunately, there is no `exists` method to determine if a key exists within Keychain & Keystore. This makes it difficult to check if a key exists before getting its value in the same manner for every implementation. Currently, either an error will be thrown (which can be difficult to parse) or null is returned, this introduces many outcomes that need to be accounted for. An `exists` method would account for that by only returning `true/false` for the provided key depending on if the key exists or not.

**Comment by talut** [comment]
Hi thanks for issue and thanks for PR. I merged your PR and today I'll update package at npm.
