### ISSUE TITLE
Adding new languages support for README.md

### ISSUE THREAD

**Issue by talut** [talut/rn-secure-storage#3]
Happy Hacktoberfest for everyone. If you want to help please add new language translation for README.md

**1.**
Fork my REPO
**2.**
Create new directory `docs`
**3.**
Add your tranlated README.md like `README-es.md`
**4.**
Edit README.md and add your translated `readme`file link. `/docs/README-es.md`

p.s You can use [https://shields.io/](https://shields.io/) for badge.

Also you can add translated readme files like here (Turkish translation): [https://github.com/talut/react-native-pin-view](https://github.com/talut/react-native-pin-view)

**Comment by McKay1717** [comment]
Hey !
If I understand correctly, you want some translation of the README.md ?

**Comment by talut** [comment]
@McKay1717  Yes, you understand correctly 👍

**Comment by McKay1717** [comment]
Ok thanks @talut I'll make a french version

**Comment by NayakNavin** [comment]
I can make Hindi translation

**Comment by msdeibel** [comment]
I'll do the German translation.

**Comment by fpkmatthi** [comment]
I can do a Dutch translation.

**Comment by WrightKD** [comment]
Working on an Afrikaans version.

**Comment by talut** [comment]
@McKay1717 @NayakNavin @msdeibel @fpkmatthi Thanks a lot. If you have any repo for adding Turkish translation let me know.

**Comment by Vinetos** [comment]
French done 😄

**Comment by mfaridzia** [comment]
I can do a indonesia translation.

**Comment by HenryFilho** [comment]
I have made the translation to Brazilian Portuguese. 😁

**Comment by talut** [comment]
BTW, thats enough I think 😸  I need make PR too I'm closing this issue thanks a lot all of you. Happy Hacktoberfest ❤️
