### ISSUE TITLE
The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'RNSecureStorage')

### ISSUE THREAD

**Issue by Deg5112** [talut/rn-secure-storage#38]
Hello, I am currently running a iphone X simulator with software version 12.4

Yet i still see this warning

The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'RNSecureStorage')

Is this accurate? Any steps to remove the warning?

Thanks,

-Dave

**Comment by talut** [comment]
Sorry, this package supporting only Target 8.0 and after. You . should update deployment target to 8.0 or later.
