### ISSUE TITLE
Remove "buildToolsVersion '28.0.2'" from build.gradle file

### ISSUE THREAD

**Issue by MrAusnadian** [talut/rn-secure-storage#39]
I get the following warning when using rn-secure-storage:

> Configure project :rn-secure-storage
> WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.2.
> Android SDK Build Tools 28.0.3 will be used.
> To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by MrAusnadian** [comment]
Related Pull Request: https://github.com/talut/rn-secure-storage/pull/40

**Comment by Deg5112** [comment]
is this merged yet?

**Comment by MrAusnadian** [comment]
For some reason, it isn't. Need someone with write access to do it

**Comment by talut** [comment]
Hi, sorry for the long wait. I merged PR, update version and publish the package.
