### ISSUE TITLE
Deprecation: 'libcore.io.Memory' was not found

### ISSUE THREAD

**Issue by makarkotlov** [talut/rn-secure-storage#41]
Thank you for a great lib! Deprecation doesn't crash the build but it shows warnings when bundling the release

![image](https://user-images.githubusercontent.com/32848434/67853415-92628980-fb1f-11e9-92ea-19b608da54cd.png)

**Comment by talut** [comment]
Hi @makarkotlov  thanks for the issue. I'll look up as soon as possible.

**Comment by makarkotlov** [comment]
Not reproducing anymore
