### ISSUE TITLE
Why use ECB mode when is not recommended? but used in this project.

### ISSUE THREAD

**Issue by guidux** [talut/rn-secure-storage#45]
First of all my knowledge of cryptography is limited that's why I ask this questions.

This question is because in a recent Etical Hacking - Static Code Analysis applied to my codebase states that ECB is a weak method [CWE-327: Use of a Broken or Risky Cryptographic Algorithm](https://cwe.mitre.org/data/definitions/327.html)

I read some sites when states that ECB mode is not recommended since for the same input produce identical output. [Block cipher mode of operation](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation ) Furthermore, CWE - 327 encourage not to use algorithms such as MD4, MD5, SHA1, DES. In fact DES is used in combination with ECB. 

However I look to the library codebase and find out that RSA/ECB is used.  I run my own tests and realize that the SKS_DATA_FILE and SKS_KEY_FILE files  have different content for the same input. This tells me that a good approach was implemented when writing the code.

Would anyone provide any explanation about how the library implemented cryptography to have better understanding of ECB in this project?

**Comment by talut** [comment]
I fork Android side from another package but right now I'm re writing this package with newer algorithm. But Android side is a little bit difficult when I'll handle Android siide I'll update package with a lot of feature (removeAll items etc.)

**Comment by jpstotz** [comment]
ECB mode is still used, now in combination with AES, but it is still a security risk as ECB mode is insecure.
