### ISSUE TITLE
Use of a Broken or Risky CryptographicAlgorithm

### ISSUE THREAD

**Issue by egaleme** [talut/rn-secure-storage#49]
Hello,
I recently used rn-secure-storage for a banking app instead of AsyncStorage but got this error from a veracode scan : Use of a Broken or Risky CryptographicAlgorithm.

Please how do i go about in solving this issue of security?

**Comment by talut** [comment]
Hi, right now I'm re writing this package with newer algorithm. But Android side is a little bit difficult when I'll handle ANdroid siide I'll update package with a lot of feature (removeAll items etc.)
