### ISSUE TITLE
[Error: Non interactive decryption mode.] in Android

### ISSUE THREAD

**Issue by ShivamJoker** [talut/rn-secure-storage#58]
While retrieving the data in android I get `[Error: Non interactive decryption mode.]` using 
```js
 RNSecureStorage.getItem('token')
        .then((res) => {
          console.log(res);
        })
        .catch((err) => {
          console.log(err);
        });
```
It works fine in iOS

**Comment by ShivamJoker** [comment]
Any updates on this ?

**Comment by Talha-Jawed** [comment]
any update?

**Comment by ladiandrasi** [comment]
I am seeing the same issue.
Any updates?

**Comment by talut** [comment]
I'm trying to re-write android part. Most probably I'm gonna use Jetpack Security Library -> https://developer.android.com/topic/security/data
