### ISSUE TITLE
Remove multiple values at a time

### ISSUE THREAD

**Issue by manoj-cervoo** [talut/rn-secure-storage#60]
Is it possible to remove multiple values by single call?

`RNSecureStorage.remove("key1", "key12").then((val) => {
console.log(val)
}).catch((err) => {
console.log(err)
});`

**Comment by talut** [comment]
I just released v3.0.0 and it does remove / set / get multiple values.

Please check the new version and Readme file. It also includes a few new features as well.

It's tested with the newest RN versions.
