### ISSUE TITLE
Error running on Android

### ISSUE THREAD

**Issue by mvmcorrea** [talut/rn-secure-storage#64]
![image](https://user-images.githubusercontent.com/230940/131504247-0dc7fa1c-b20b-4437-a6c8-af2cf47342f4.png)

null is not an object (evaluating '_rnsecurestorage.default.set')

Anybody can help with that ?

**Comment by Talha-Jawed** [comment]
@mvmcorrea hi, did you found any solution?

**Comment by Talha-Jawed** [comment]
### How I have solved this error:

1. clean Gradle
`cd ./android && ./gradlew clean && cd ..`

2. start the Android app with
`react-native run-android`

**If these solutions didn't work remove your node_modules folder and re-install**

**Comment by mvmcorrea** [comment]
Tks @Talha-Jawed ...
