### ISSUE TITLE
Read values from native code

### ISSUE THREAD

**Issue by Romick2005** [talut/rn-secure-storage#65]
Is there a way to read values from storage from native code? For example I need to set auth request to the server from native part and auth token is stored by JS code.

**Comment by talut** [comment]
You should be able to access this functionality.

To understand how data is stored, you can refer to the source code of my library. In it, you'll find that all data is stored in the keychain using the following format:

```
let keyData = appBundleName + "." + key
```

This means you can access and read the data directly from the Keychain using the concatenated string of the app's bundle name and the specific key.


## UPDATE

I just released v3.0.0

Please check the new version and Readme file. It also includes a few new features as well.
