### ISSUE TITLE
Obsolete build.gradle

### ISSUE THREAD

**Issue by lorenzogatti** [talut/rn-secure-storage#66]
Compiling a React Native app for Android with Windows 10, Gradle 7.2, OpenJDK 11.

Gradle 7.2 doesn't like rn-secure-storage\\**android\build.gradle**:
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

Offending code:
```
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```
Property "**compile**" is deprecated since Gradle 6 and removed since Gradle 7 and it has been replaced by "**implementation**". This works:

```
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}
```

**Comment by lorenzogatti** [comment]
Thank you, iruAiweapps! Any chance of an updated release on npm? This library seems a bit abandoned.

**Comment by corlissc** [comment]
Any idea on when this will be released? Currently, I'm having to manually update the build.gradle file each time I run a yarn add command.

**Comment by coprocoder** [comment]
Please update the library. Fix one line, it's not hard.
Your library is good, but getting into the sources every time is very annoying

**Comment by corlissc** [comment]
Please merge Pull Request https://github.com/talut/rn-secure-storage/pull/68

**Comment by affansk** [comment]
@coprocoder  plz use this https://www.npmjs.com/package/patch-package

**Comment by minaGergess** [comment]
will crash for release build if we change from configurations.compile to from configurations.implementation

**Comment by AlixH** [comment]
Up :)

**Comment by talut** [comment]
Please check v2.0.8
