### ISSUE TITLE
[Question]: How is the data retrieved on iOS

### ISSUE THREAD

**Issue by AlixH** [talut/rn-secure-storage#67]
I would like to know what element of an iOS app is used to retieve its corresponding data. (an id perhaps)
I have done an app transfer after which my App ID has changed but the bundle ID remained the same. After updating the app, I have lost all the data in the secured storage.SO my opinion is that the data is bound to the App ID that is
`<teamdID>:<bundleID>.`
 I am using 2.0.7

**Comment by talut** [comment]
Unfortunately, I'm uncertain about why this issue has occurred. I believe that the data should be bound to the app's bundle identifier, which is the standard approach in app development. Further investigation might be needed to understand the discrepancy.

## UPDATE

I just released v3.0.0

Please check the new version and Readme file. It also includes a few new features as well.
