### ISSUE TITLE
[Feature] Support kSecAttrSynchronizable to allow sync data between ios devices

### ISSUE THREAD

**Issue by raphaelpare** [talut/rn-secure-storage#74]
Currently, it seems that the lib does not support the optional flag "kSecAttrSynchronizable" to allow syncing the keychain data between devices thanks to icloud capabilities.

This is useful to ensure sensitive data is kept between devices or when a user recover his ios data on a new device

**Comment by talut** [comment]
Hey @raphaelpare thanks for the issue; I just released v3.0.0. 

I didn't add this optional flag yet. But as soon as possible I'll look at it.

Please check the new version and Readme file. It also includes a few new features as well.
